/* lessons.js — 생성기(kiip_gen.js)가 전 과 데이터로 자동 생성. 손으로 고치지 마세요.
 * Auto-generated from all lesson data files. Do not edit by hand. */
var LESSONS = [
  {"n":1,"date":"","title":"모음과 인사","en":"Vowels and Greetings","ready":true,"cats":[{"id":"all","label":"전체 All"},{"id":"vowel","label":"모음 Vowels"},{"id":"word","label":"단어 Words"},{"id":"greet","label":"인사 Greetings"}],"cards":[{"type":"letter","cat":"vowel","kind":"모음 vowel","sz":"v","say":"아","au":"audio/L1-01.m4a","glyph":"ㅏ","rom":"a","m":[118,96,false],"ko":"입을 크게 벌려요.","en":"Open wide. Lips flat.","warn":false,"word":"아이","gloss":"child"},{"type":"letter","cat":"vowel","kind":"모음 vowel","sz":"v","say":"이","au":"audio/L1-02.m4a","glyph":"ㅣ","rom":"i","m":[140,34,false],"ko":"입을 옆으로 펴요.","en":"Spread wide, like a smile.","warn":false,"word":"이","gloss":"tooth"},{"type":"letter","cat":"vowel","kind":"모음 vowel","sz":"v","say":"우","au":"audio/L1-03.m4a","glyph":"ㅜ","rom":"u","m":[64,58,true],"ko":"입술을 동그랗게 모아 내밀어요.","en":"ROUND lips. Push forward.","warn":false,"word":"우","gloss":""},{"type":"letter","cat":"vowel","kind":"모음 vowel","sz":"v","say":"오","au":"audio/L1-04.m4a","glyph":"ㅗ","rom":"o","m":[92,78,true],"ko":"입술을 동그랗게, ㅜ보다 조금 더 벌려요.","en":"Round, a bit more open than ㅜ.","warn":false,"word":"오 · 오이","gloss":"five · cucumber"},{"type":"letter","cat":"vowel","kind":"모음 vowel","sz":"v","say":"으","au":"audio/L1-05.m4a","glyph":"ㅡ","rom":"eu","m":[140,26,false],"ko":"입술을 옆으로 펴요. 둥글게 하지 마세요.","en":"FLAT lips. NEVER round.","warn":true,"word":"으","gloss":""},{"type":"item","cat":"word","kind":"단어 word","sz":"g2","say":"아이","au":"audio/L1-06.m4a","glyph":"아이","rom":"a-i","mean":"child","when":"1과 · Lesson 1"},{"type":"item","cat":"word","kind":"단어 word","sz":"g2","say":"오이","au":"audio/L1-07.m4a","glyph":"오이","rom":"o-i","mean":"cucumber","when":"1과 · Lesson 1"},{"type":"item","cat":"word","kind":"단어 word","sz":"g2","say":"이","au":"audio/L1-08.m4a","glyph":"이","rom":"i","mean":"tooth","when":"1과 · Lesson 1"},{"type":"item","cat":"word","kind":"단어 word","sz":"g2","say":"오","au":"audio/L1-09.m4a","glyph":"오","rom":"o","mean":"five","when":"1과 · Lesson 1"},{"type":"item","cat":"greet","kind":"인사 greeting","sz":"g2","say":"안녕하세요","au":"audio/L1-10.m4a","glyph":"안녕하세요?","rom":"an-nyeong-ha-se-yo","mean":"Hello.","when":"아침·점심·저녁 모두 · 통째로 / any time of day · as a whole"},{"type":"item","cat":"greet","kind":"인사 greeting","sz":"g2","say":"안녕히 가세요","au":"audio/L1-11.m4a","glyph":"안녕히 가세요.","rom":"an-nyeong-hi ga-se-yo","mean":"Goodbye.","when":"가는 사람에게 · 통째로 / to the person LEAVING · as a whole"},{"type":"item","cat":"greet","kind":"인사 greeting","sz":"g2","say":"안녕히 계세요","au":"audio/L1-12.m4a","glyph":"안녕히 계세요.","rom":"an-nyeong-hi gye-se-yo","mean":"Goodbye.","when":"남는 사람에게 · 통째로 / to the person STAYING · as a whole"},{"type":"item","cat":"greet","kind":"인사 greeting","sz":"g2","say":"감사합니다","au":"audio/L1-13.m4a","glyph":"감사합니다.","rom":"gam-sa-ham-ni-da","mean":"Thank you.","when":"언제나 공손하게 · 통째로 / always polite · as a whole"}]},
  {"n":2,"date":"","title":"자음 ㄴㅁㄹ","en":"Consonants ㄴ ㅁ ㄹ","ready":false,"cats":[],"cards":[]},
  {"n":3,"date":"","title":"ㅓ와 반모음","en":"ㅓ and ㅑ ㅕ ㅛ ㅠ","ready":false,"cats":[],"cards":[]},
  {"n":4,"date":"","title":"평음 ㅂㄷㄱㅅㅈ","en":"Plain consonants","ready":false,"cats":[],"cards":[]},
  {"n":5,"date":"","title":"격음 ㅍㅌㅋㅊㅎ","en":"Aspirated consonants","ready":false,"cats":[],"cards":[]},
  {"n":6,"date":"","title":"경음 ㅃㄸㄲㅆㅉ","en":"Tense consonants","ready":false,"cats":[],"cards":[]},
  {"n":7,"date":"","title":"3중 대립","en":"Three sounds: plain · aspirated · tense","ready":false,"cats":[],"cards":[]},
  {"n":8,"date":"","title":"받침 1","en":"Final consonants 1 (ㄴ ㅁ ㅇ ㄹ)","ready":false,"cats":[],"cards":[]},
  {"n":9,"date":"","title":"받침 2","en":"Final consonants 2 (ㄱ ㄷ ㅂ)","ready":false,"cats":[],"cards":[]},
  {"n":10,"date":"","title":"연음","en":"Linking sounds","ready":false,"cats":[],"cards":[]},
  {"n":11,"date":"","title":"받침·연음 낭독","en":"Reading aloud","ready":false,"cats":[],"cards":[]},
  {"n":12,"date":"","title":"ㅐㅔㅚㅟ","en":"Vowels ㅐ ㅔ ㅚ ㅟ","ready":false,"cats":[],"cards":[]},
  {"n":13,"date":"","title":"남은 모음","en":"The rest of the vowels","ready":false,"cats":[],"cards":[]},
  {"n":14,"date":"","title":"종합 낭독","en":"Reading it all together","ready":false,"cats":[],"cards":[]}
];
